### ISSUE TITLE
每段时间点第一个活动开始时的提醒都会让应用崩溃

### ISSUE THREAD

**Issue by MKStoler4096** [Class-Widgets/Class-Widgets#137]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不崩溃

### 实际结果

崩溃啦！/_ \

### 重现步骤

用我上次的课表和 Actions 构建的应用，等待第一节课

### 堆栈跟踪（可选）

```shell
崩溃三次均无日志记录。
```

### 应用版本

1.1.7-b3

### 操作系统版本

10.0.26100

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by RinLit-233-shiroko** [comment]
emm……没能复现

**Comment by MKStoler4096** [comment]
这是个玄学问题，概率复现（）

**Comment by RinLit-233-shiroko** [comment]
> 另外一个奇怪的崩溃，原因不详：
> 
> ```
> RuntimeError: wrapped C/C++ object of type ListWidget has been deleted
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "d:\文档\GitHub\Class-Widgets\main.py", line 745, in update_time
>     mgr.update_widgets()
>   File "d:\文档\GitHub\Class-Widgets\main.py", line 468, in update_widgets
>     widget.update_data(path=widget.path)
>   File "d:\文档\GitHub\Class-Widgets\main.py", line 865, in update_data
>     cd_list = get_countdown(toast=True)
>   File "d:\文档\GitHub\Class-Widgets\main.py", line 178, in get_countdown
>     tip_toast.main(3, next_lessons[0])  # 准备上课（预备铃）
>   File "d:\文档\GitHub\Class-Widgets\tip_toast.py", line 266, in main
>     setTheme(Theme.AUTO)
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 414, in setTheme
>     updateStyleSheet(lazy)
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 388, in updateStyleSheet
>     setStyleSheet(widget, file, qconfig.theme)
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 326, in setStyleSheet
>     widget.setStyleSheet(getStyleSheet(source, theme))
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 300, in getStyleSheet
>     return applyThemeColor(source.content(theme))
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in content
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 258, in <listcomp>
>     return '\n'.join([i.content(theme) for i in self.sources])
>   File "D:\文档\GitHub\Class-Widgets\.venv\lib\site-packages\qfluentwidget
> s\common\style_sheet.py", line 219, in content
>     return self.darkStyleSheet()
> SystemError: _PyEval_EvalFrameDefault returned a result with an exception
> set
> ```

找到原因了，与 #205 原因一致，已修复。不过此Issue还能复现吗，不能就close了

**Comment by xuanxuan1231** [comment]
> 找到原因了，与 #205 原因一致，已修复。不过此Issue还能复现吗，不能就close了

#212 复现了
