### ISSUE TITLE
新版本中的Test Plugin报错

### ISSUE THREAD

**Issue by SparkleUesegi** [Class-Widgets/Class-Widgets#161]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

打开时不会弹出错误提示

### 实际结果

![image](https://github.com/user-attachments/assets/ba3454f5-f5e8-42f3-a74c-d67264c9e2f8)

### 重现步骤

安装 [构建#68](https://github.com/Class-Widgets/Class-Widgets/actions/runs/11996753657) 及以后的构建后启动即可

### 堆栈跟踪（可选）

```shell
Traceback (most recent call last):
  File "main.py", line 1334, in <module>
  File "main.py", line 356, in run_plugins
  File "C:\Users\Administrator\Downloads\Windows-x64\plugins\test\main.py", line 33, in execute
    contentLayout = self.test_widget.findChild(QHBoxLayout, 'contentLayout')  # 标题布局
AttributeError: 'NoneType' object has no attribute 'findChild'
```

### 应用版本

1.1.7_b4 构建 #68: Commit 83589e5 pushed by RinLit-233-shiroko

### 操作系统版本

11.0.22631.4317

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by SparkleUesegi** [comment]
经过测试，只要删除 Test Plugin 就能正常使用
