### ISSUE TITLE
v1.1.7版本设置无法打开，并且打开时程序崩溃退出

### ISSUE THREAD

**Issue by creeeeeeeeepersama** [Class-Widgets/Class-Widgets#210]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

原本想试一试新的版本，正好作息时间和课表也换了，就想着重新写一张课表出来

### 实际结果

然后打开设置的时候先是程序未响应，然后就闪退了（我也不确定是不是程序自身的问题还是我们班大屏神经了，是i5 3代+4G qwq）

### 重现步骤

右键了任务栏的图标，然后点设置，就挂了

### 应用版本

1.1.7 beta4

### 操作系统版本

22H2 19045.5247 win10

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by creeeeeeeeepersama** [comment]
我可以再试试1.1.6.5版本的，但是就像是#98[https://github.com/Class-Widgets/Class-Widgets/issues/98](url) 里面所写，我们班之前也是这样，并且导入之后应用再也打不开了，虽然之前在B站反馈过一次，但是好像没有得到彻底解决

**Comment by creeeeeeeeepersama** [comment]
顺带一提，我们班插件广场似乎（似   乎）也打不开，后续将进行一下更多的尝试

**Comment by RinLit-233-shiroko** [comment]
![image](https://github.com/user-attachments/assets/1fdfc4f1-1cd5-45ec-9063-cb5bc2a3f2e5)
啊这……
在默认配置（删掉config.ini）的情况下能正常打开吗，在您的个人电脑上能打开吗；
插件广场打不开是指什么呢，卡在启动画面还是？

**Comment by RinLit-233-shiroko** [comment]
关于插件广场：在部分设备上会无法访问，已在 77bb33a 修复；可在Release页面或QQ群中下载最新版

**Comment by creeeeeeeeepersama** [comment]
个人电脑还没试过，删除ini这个事情我放学再试试吧
插件广场就是卡在启动页面，如果 77bb33a 已经修复那就没关系了
谢谢

**Comment by creeeeeeeeepersama** [comment]
1.6update
删除ini无效
最近感冒了有点不舒服可能没太长时间调试

**Comment by RinLit-233-shiroko** [comment]
现在打开设置还能崩溃吗？ @creeeeeeeeepersama

**Comment by AntY091123** [comment]
本人在win7系统上也遇到了此问题 但是换到非中文路径就能正常打开设置 疑似和 #221 重复

**Comment by AntY091123** [comment]
补充：使用最新构建问题依旧

**Comment by xuanxuan1231** [comment]
@AntY091123 @creeeeeeeeepersama 最近试着修了一下 现在还崩溃吗？

**Comment by AntY091123** [comment]
@xuanxuan1231 使用最新构建甚至连任务栏图标的右键菜单都点不开（？

<details>
    <summary>日志</summary>

> 2025-01-31 22:30:54.010 | INFO     | __main__:<module>:87 - 未禁用日志输出
2025-01-31 22:30:54.011 | INFO     | __main__:<module>:1670 - 当前缩放系数：100.0%
2025-01-31 22:30:54.020 | INFO     | __main__:<module>:1686 - 共享内存：True 是否允许多开实例：0
2025-01-31 22:30:54.020 | INFO     | __main__:<module>:1687 - 操作系统：Windows，版本：6.1.7601/7
2025-01-31 22:30:55.689 | INFO     | __main__:init:1637 - 应用主题：default
2025-01-31 22:30:55.726 | ERROR    | __main__:global_exceptHook:105 - 全局异常捕获：<class 'NotImplementedError'>  <traceback object at 0x00000000065FB740>
2025-01-31 22:30:55.727 | ERROR    | __main__:global_exceptHook:106 - 详细堆栈信息：
Traceback (most recent call last):
  File "qfluentwidgets\common\theme_listener.py", line 17, in run
  File "darkdetect\_dummy.py", line 19, in listener
NotImplementedError
2025-01-31 22:30:55.746 | INFO     | __main__:get_weather_data:1420 - 获取天气数据

</details>

**Comment by xuanxuan1231** [comment]
之前群里也有同学反馈过这个问题，是因为 qfluentwidgets 引用了一个 win7 不支持的库 `darkdetect`（这个库需要 win10），所以导致了崩溃

**Comment by RinLit-233-shiroko** [comment]
> 之前群里也有同学反馈过这个问题，是因为 qfluentwidgets 引用了一个 win7 不支持的库 `darkdetect`（这个库需要 win10），所以导致了崩溃

我记得我做过处理了

**Comment by RinLit-233-shiroko** [comment]
我再看看

**Comment by RinLit-233-shiroko** [comment]
> 我再看看

传了，再看看 @AntY091123 @creeeeeeeeepersama

**Comment by AntY091123** [comment]
@RinLit-233-shiroko 最新构建问题依旧（指打不开右键菜单）

**Comment by AntY091123** [comment]
补充：在最新的正式版 `v1.1.7` 也出现了打不开右键菜单的问题
历史版本`v1.1.7 - b4` 则可以正常打开右键菜单 （打开设置仍然会崩溃）

**Comment by AntY091123** [comment]
似乎是一个新的bug（？）

**Comment by RinLit-233-shiroko** [comment]
> [@RinLit-233-shiroko](https://github.com/RinLit-233-shiroko) 最新构建问题依旧（指打不开右键菜单）

程序本身能正常启动吗

**Comment by AntY091123** [comment]
> > [@RinLit-233-shiroko](https://bgithub.xyz/RinLit-233-shiroko) 最新构建问题依旧（指打不开右键菜单）
> 
> 程序本身能正常启动吗

任务栏能出现程序图标 但是主页面并没有出现

**Comment by RinLit-233-shiroko** [comment]
> > > [@RinLit-233-shiroko](https://bgithub.xyz/RinLit-233-shiroko) 最新构建问题依旧（指打不开右键菜单）
> > 
> > 
> > 程序本身能正常启动吗
> 
> 任务栏能出现程序图标 但是主页面并没有出现

确定是 **现在的** 最新构建吗

**Comment by AntY091123** [comment]
> > > > [@RinLit-233-shiroko](https://bgithub.xyz/RinLit-233-shiroko) 最新构建问题依旧（指打不开右键菜单）
> > > 
> > > 
> > > 程序本身能正常启动吗
> > 
> > 
> > 任务栏能出现程序图标 但是主页面并没有出现
> 
> 确定是 **现在的** 最新构建吗

确定是最新构建 [https://bgithub.xyz/Class-Widgets/Class-Widgets/actions/runs/13099685899/artifacts/2523327302](url)

**Comment by RinLit-233-shiroko** [comment]
@creeeeeeeeepersama
