### ISSUE TITLE
[Bug]:点按[预备提醒]测试按钮时出现错误

### ISSUE THREAD

**Issue by Detritalw** [Class-Widgets/Class-Widgets#214]
### 检查清单

- [X] 我已更新到最新版 ![GitHub Release](https://img.shields.io/github/v/release/RinLit-233-shiroko/Class-Widgets?include_prereleases) ，并看过[最新提交](https://github.com/RinLit-233-shiroko/Class-Widgets/commits/main/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/RinLit-233-shiroko/Class-Widgets/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 实际结果

![08a64283f660816f05462fcdf01b4346](https://github.com/user-attachments/assets/135442ab-bad9-4ce8-b314-39e76388c564)

### 重现步骤

1.最新版本 1.1.7-b4 下载
2.打开设置
3.按下`预备提醒`测试按钮
4.出错

### 堆栈跟踪（可选）

```shell
2024-12-31 19:03:47.168 | INFO     | __main__:<module>:78 - 未禁用日志输出
2024-12-31 19:03:47.919 | INFO     | __main__:<module>:1498 - 共享内存：True 是否允许多开实例：0
2024-12-31 19:03:49.626 | INFO     | __main__:init:1436 - 应用主题：default
2024-12-31 19:03:49.939 | INFO     | __main__:get_weather_data:1231 - 获取天气数据
2024-12-31 19:03:50.028 | INFO     | __main__:init:1477 - 显示窗口：天气
2024-12-31 19:03:50.100 | INFO     | __main__:init:1477 - 显示窗口：活动倒计时
2024-12-31 19:03:50.106 | INFO     | __main__:init:1477 - 显示窗口：当前活动
2024-12-31 19:03:50.111 | INFO     | __main__:init:1477 - 显示窗口：更多活动
2024-12-31 19:03:50.117 | INFO     | __main__:init:1480 - Class Widgets 启动。版本: 1.1.7-b4
2024-12-31 19:03:50.212 | SUCCESS  | __main__:update_weather_data:1254 - 已获取天气数据
2024-12-31 19:03:50.946 | INFO     | __main__:get_weather_data:1231 - 获取天气数据
2024-12-31 19:03:51.110 | SUCCESS  | __main__:update_weather_data:1254 - 已获取天气数据
2024-12-31 19:03:57.634 | INFO     | __main__:open_settings:1279 - 打开“设置”
2024-12-31 19:04:00.897 | INFO     | __main__:open_exact_menu:1294 - 打开“额外选项”
2024-12-31 19:04:37.458 | INFO     | tip_toast:__init__:90 - 预备铃声显示
2024-12-31 19:04:38.051 | ERROR    | __main__:global_exceptHook:93 - 全局异常捕获：<class 'SystemError'> PyEval_EvalFrameEx returned a result with an error set <traceback object at 0x000002731EC0F940>
2024-12-31 19:04:38.051 | ERROR    | __main__:global_exceptHook:94 - 详细堆栈信息：
RuntimeError: wrapped C/C++ object of type ListWidget has been deleted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "menu.py", line 465, in <lambda>
  File "tip_toast.py", line 405, in push_notification
  File "tip_toast.py", line 362, in main
  File "tip_toast.py", line 95, in __init__
  File "qfluentwidgets\common\style_sheet.py", line 512, in setThemeColor
  File "qfluentwidgets\common\style_sheet.py", line 388, in updateStyleSheet
  File "qfluentwidgets\common\style_sheet.py", line 326, in setStyleSheet
  File "qfluentwidgets\common\style_sheet.py", line 300, in getStyleSheet
  File "qfluentwidgets\common\style_sheet.py", line 258, in content
  File "qfluentwidgets\common\style_sheet.py", line 258, in <listcomp>
  File "qfluentwidgets\common\style_sheet.py", line 219, in content
SystemError: PyEval_EvalFrameEx returned a result with an error set
```

### 应用版本

1.1.7-b4

### 操作系统版本

Windows 11 24H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Detritalw** [comment]
![QQ_1735643396866](https://github.com/user-attachments/assets/9f5f0d89-8dfb-488d-8e22-89b36495e3f9)
已有相同情况发生
